In [ ]:
!unzip '/content/drive/MyDrive/Twitter Sentiment.zip'

Archive:  /content/drive/MyDrive/Twitter Sentiment.zip
  inflating: Twitter_Data.csv        


In [ ]:
import spacy
nlp=spacy.load('en_core_web_sm')

In [ ]:
import pandas as pd

df=pd.read_csv('/content/Twitter_Data.csv')
# dataset=df['clean_text'][:5000]
df.head()
positive = df[df['category'] == 1]['clean_text']
neutral = df[df['category'] == 0]['clean_text']
negative = df[df['category'] == -1]['clean_text']


In [ ]:
positive_sample = positive.sample(n=2000, random_state=42).tolist()
neutral_sample = neutral.sample(n=2000, random_state=42).tolist()
negative_sample = negative.sample(n=2000, random_state=42).tolist()

In [ ]:
sample = positive_sample + neutral_sample + negative_sample
print(sample)

['this nyay scheme the retrd will game changer for sure most people voted for modi 2014 with hopes getting lakhs their account the mindset poor our country set receive freebies ', 'special thanks for recognising work done yers congress rule drdo was set nehruji 1958 aset programme which now lauded modi was approv drmanmohan singh ', 'yes absolutely right jai shri ram jai bharat vande matram only modi ', 'cong time mein every mission source fund khud dirty netaon duara hadap liya jata thhajabki modi every mission liye openhearted fund dete heindesh suraksha liye modi best world leader ', 'lost dont have answer \ncoz knew democracy wins when they elect leader who works for all for those who vote him and also for those who didnt democy failed electing then cldnt think any other right person cant debate upon that ', 'compare rahul gandhi with narender modi one knows acting and another knows what can doone knows jumlebaji and another knows which thing possible for better india', 'modi says 

In [ ]:
positive_list = [1] * 2000
neutral_list = [0] * 2000
negative_list = [-1] * 2000

sample_labels = positive_list + neutral_list + negative_list
print(sample_labels)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [ ]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Embedding
# define documents
Sent = [str(sentence) for sentence in sample]

In [ ]:
sent_labels = sample_labels

In [ ]:
# integer encoding of the documents
my_vocab_size = 30
encoded_sent = [one_hot(i, my_vocab_size) for i in Sent]
print(encoded_sent)

[[16, 26, 12, 7, 3, 8, 13, 20, 25, 26, 6, 24, 4, 25, 22, 25, 27, 5, 27, 6, 27, 17, 7, 17, 27, 28, 10, 15, 25, 17], [16, 8, 25, 22, 4, 26, 25, 16, 3, 7, 21, 15, 1, 9, 15, 3, 2, 18, 2, 22, 21, 8, 9, 5], [7, 7, 17, 8, 10, 12, 8, 19, 20, 15, 6, 22], [13, 21, 28, 20, 20, 2, 11, 20, 7, 16, 28, 27, 9, 20, 14, 22, 20, 20, 18, 5, 11, 20, 7, 13, 18, 22, 4, 11, 4], [7, 28, 2, 1, 18, 2, 14, 18, 21, 14, 15, 4, 5, 9, 25, 14, 25, 22, 5, 28, 3, 26, 14, 25, 22, 5, 27, 10, 21, 8, 23, 10, 16, 4, 7, 17, 18, 24, 5, 5, 4], [27, 29, 2, 27, 7, 22, 12, 29, 6, 26, 10, 29, 19, 23, 13, 29, 23, 26, 10, 29, 2, 18, 26, 25, 15, 10], [22, 15, 14, 17], [22, 16, 25, 10, 26, 25, 11, 27, 26, 21, 1, 10, 14, 28, 4, 10, 14, 11, 8, 11, 8, 19], [18, 25, 22, 29, 8, 11, 7, 25, 26, 18, 14, 11, 12, 28, 4, 28], [17, 24, 18, 26, 1, 12, 28, 22, 14, 22, 14, 4, 21, 2, 7, 12, 7, 22, 3, 25, 27, 3, 19, 25, 1, 4, 7, 20, 1, 12, 13], [11, 9, 16, 20, 12, 28, 2, 6, 10, 25, 19, 22, 5, 22, 25, 6, 5, 8, 22, 13, 25, 28, 17, 18, 28, 2, 10, 8, 11, 8

In [ ]:
# padding documents to a max length =5
length = 5
padded_sent = pad_sequences(encoded_sent, maxlen=length, padding='pre')
print(padded_sent)

[[28 10 15 25 17]
 [22 21  8  9  5]
 [19 20 15  6 22]
 ...
 [ 1  4  7  7 22]
 [29 21 22  7 22]
 [28 25  6  9 15]]


In [ ]:
import numpy as np
from keras.models import Sequential
from keras.layers import Embedding, Flatten, Dense, Dropout
from keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
X = np.array(padded_sent)
y = np.array(sample_labels)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

# Define the model
mymodel = Sequential()
mymodel.add(Embedding(my_vocab_size, 8, input_length=length))
mymodel.add(Flatten())
mymodel.add(Dense(32, activation='relu'))
mymodel.add(Dropout(0.5))
mymodel.add(Dense(1, activation='tanh'))  # Use tanh activation for labels -1, 0, 1

# Compile the model
mymodel.compile(optimizer='adam', loss='mse', metrics=['accuracy'])  # Use mean squared error loss for regression task

# Fit the model
history = mymodel.fit(X_train, y_train, epochs=30, batch_size=64, validation_data=(X_test, y_test), verbose=1)

# Evaluate the model
model_loss, model_accuracy = mymodel.evaluate(X_test, y_test, verbose=0)
print('Accuracy: %.2f%%' % (model_accuracy * 100))

Epoch 1/30
75/75 [==============================] - 1s 6ms/step - loss: 0.6648 - accuracy: 0.3375 - val_loss: 0.6841 - val_accuracy: 0.3167
Epoch 2/30
75/75 [==============================] - 0s 4ms/step - loss: 0.6611 - accuracy: 0.3375 - val_loss: 0.6843 - val_accuracy: 0.3167
Epoch 3/30
75/75 [==============================] - 0s 3ms/step - loss: 0.6598 - accuracy: 0.3375 - val_loss: 0.6833 - val_accuracy: 0.3167
Epoch 4/30
75/75 [==============================] - 0s 3ms/step - loss: 0.6573 - accuracy: 0.3375 - val_loss: 0.6850 - val_accuracy: 0.3167
Epoch 5/30
75/75 [==============================] - 0s 3ms/step - loss: 0.6564 - accuracy: 0.3375 - val_loss: 0.6859 - val_accuracy: 0.3167
Epoch 6/30
75/75 [==============================] - 0s 3ms/step - loss: 0.6533 - accuracy: 0.3375 - val_loss: 0.6868 - val_accuracy: 0.3167
Epoch 7/30
75/75 [==============================] - 0s 3ms/step - loss: 0.6532 - accuracy: 0.3375 - val_loss: 0.6856 - val_accuracy: 0.3167
Epoch 8/30
75/75 [==

In [ ]:
# import numpy as np

# # Convert sent_labels to a numpy array
# sent_labels = np.array(sent_labels)

# # Fit the model
# mymodel.fit(padded_sent, sent_labels, epochs=30)

# # Evaluate the model
# model_loss, model_accuracy = mymodel.evaluate(padded_sent, sent_labels, verbose=0)
# print('Accuracy: %.2f' % (model_accuracy * 100))


In [ ]:
mysent_to_predict = ['this nyay scheme the retrd will game changer for sure most people voted for modi 2014 with hopes getting lakhs their account the mindset poor our country set receive freebies',
                     'hamaybe modis got some tapes sonia thats why shes given',
                      'because modi knows situation ground all time worst']


In [ ]:
encoded = [one_hot(d, my_vocab_size) for d in mysent_to_predict]
mypadded = pad_sequences(encoded, maxlen=length, padding='pre')

In [ ]:
y_pred = mymodel.predict(mypadded)
print(y_pred)

1/1 [==============================] - 0s 205ms/step
[[ 0.01825864]
 [-0.19668527]
 [ 0.00345334]]


In [ ]:
def classify_sentiment(prediction):
    if prediction > 0.005:
        return 1
    elif prediction < 0:
        return -1
    else:
        return 0

y_pred_labels = [classify_sentiment(pred) for pred in y_pred.flatten()]
print(y_pred_labels)

[1, -1, 0]
