In [12]:
import numpy as np

m1=[[1,2],
    [2,3],
    [4,5]]
m2=[[1,2,3,4],
    [2,3,3,6],]

print(len(m1),len(m1[0]))
print(len(m2),len(m2[0]))

3 2
2 4


In [31]:
mul=[]
row=[]
calc=0
for i in range(len(m1)):
  row=[]
  for k in range(len(m2[0])):
    # row=[]
    for j in range(len(m1[0])):
      calc+=m1[i][j]*m2[j][k]
      # print(m1[i][j],m2[j][k])
    row.append(calc)
    calc=0
    # print(row)
  mul.append(row)

print(mul)


[[5, 8, 9, 16], [8, 13, 15, 26], [14, 23, 27, 46]]


In [25]:
mn1=np.array(m1)
mn2=np.array(m2)

In [26]:
mn1

array([[1, 2],
       [2, 3],
       [4, 5]])

In [27]:
mn2

array([[1, 2, 3, 4],
       [2, 3, 3, 6]])

In [28]:
np.dot(m1,m2)

array([[ 5,  8,  9, 16],
       [ 8, 13, 15, 26],
       [14, 23, 27, 46]])

In [1]:
def count_word_occurrences(file_path):
    word_count = {}
    with open(file_path, 'r') as file:
        for line in file:
            words = line.split()
            for word in words:
                # Removing punctuation and converting to lowercase
                word = word.strip('.,!?:;"\'').lower()
                if word:
                    word_count[word] = word_count.get(word, 0) + 1
    return word_count

def main():
    file_path = input("Enter the path to the text file: ")
    try:
        word_count = count_word_occurrences(file_path)
        for word, count in word_count.items():
            print(f"{word}: {count}")
    except FileNotFoundError:
        print("File not found. Please enter a valid file path.")

if __name__ == "__main__":
    main()


Enter the path to the text file: C:\Users\91932\Downloads\bda\sample.txt
fhv: 1
ujfyb: 1
igb: 1
mg86gbk: 1
g86ygib: 1
ufb: 1
mftub: 1
hjv: 1


In [ ]:
import multiprocessing

def matrix_multiplication(A, B):
    rows_A = len(A)
    cols_A = len(A[0])
    rows_B = len(B)
    cols_B = len(B[0])

    if cols_A != rows_B:
        print("Matrix multiplication is not possible")
        return None

    result = [[0 for _ in range(cols_B)] for _ in range(rows_A)]

    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                result[i][j] += A[i][k] * B[k][j]
                # Visualize each multiplication step
                print(f"Multiplying {A[i][k]} from matrix A with {B[k][j]} from matrix B")

    return result

def compute_element(args):
    i, j, A, B = args
    result = 0
    for k in range(len(A[0])):
        result += A[i][k] * B[k][j]
    return (i, j, result)

def matrix_multiplication_parallel(A, B):
    rows_A = len(A)
    cols_B = len(B[0])

    if len(A[0]) != len(B):
        print("Matrix multiplication is not possible")
        return None

    with multiprocessing.Pool() as pool:
        results = pool.map(compute_element, [(i, j, A, B) for i in range(rows_A) for j in range(cols_B)])

    result = [[0 for _ in range(cols_B)] for _ in range(rows_A)]
    for i, j, val in results:
        result[i][j] = val

    return result

def print_matrix(matrix, name):
    print(f"{name} matrix:")
    for row in matrix:
        print(row)

# Example matrices
matrix1 = [
    [1, 2, 3],
    [4, 5, 6],
]

matrix2 = [
    [7, 8],
    [9, 10],
    [11, 12]
]

# Print input matrices
print_matrix(matrix1, "Matrix 1")
print()
print_matrix(matrix2, "Matrix 2")
print()

# Perform matrix multiplication using normal method
result_matrix_normal = matrix_multiplication(matrix1, matrix2)

# Print the result of normal method
if result_matrix_normal:
    print("Result of matrix multiplication (Normal method):")
    print_matrix(result_matrix_normal, "Result")

print()

# Perform matrix multiplication using parallel computing
result_matrix_parallel = matrix_multiplication_parallel(matrix1, matrix2)

# Print the result of parallel computing
if result_matrix_parallel:
    print("Result of matrix multiplication (Parallel computing):")
    print_matrix(result_matrix_parallel, "Result")


Matrix 1 matrix:
[1, 2, 3]
[4, 5, 6]

Matrix 2 matrix:
[7, 8]
[9, 10]
[11, 12]

Multiplying 1 from matrix A with 7 from matrix B
Multiplying 2 from matrix A with 9 from matrix B
Multiplying 3 from matrix A with 11 from matrix B
Multiplying 1 from matrix A with 8 from matrix B
Multiplying 2 from matrix A with 10 from matrix B
Multiplying 3 from matrix A with 12 from matrix B
Multiplying 4 from matrix A with 7 from matrix B
Multiplying 5 from matrix A with 9 from matrix B
Multiplying 6 from matrix A with 11 from matrix B
Multiplying 4 from matrix A with 8 from matrix B
Multiplying 5 from matrix A with 10 from matrix B
Multiplying 6 from matrix A with 12 from matrix B
Result of matrix multiplication (Normal method):
Result matrix:
[58, 64]
[139, 154]

